# Generated by Django 5.0.3 on 2024-04-17 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalRealizeEncerradas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, null=True)),
                ('nome', models.CharField(max_length=100, null=True)),
                ('tipoAnalise', models.CharField(max_length=100, null=True)),
                ('produto', models.CharField(max_length=100, null=True)),
                ('cartao', models.CharField(max_length=100, null=True)),
                ('canal', models.CharField(max_length=100, null=True)),
                ('captacao', models.CharField(max_length=100, null=True)),
                ('numeroProposta', models.CharField(max_length=100, null=True)),
                ('situacao', models.CharField(max_length=100, null=True)),
                ('dataInicio', models.CharField(max_length=100, null=True)),
                ('horaInicio', models.CharField(max_length=100, null=True)),
                ('dataFim', models.CharField(max_length=100, null=True)),
                ('horaFim', models.CharField(max_length=100, null=True)),
                ('tempoFila', models.CharField(max_length=100, null=True)),
                ('tempoAnalise', models.CharField(max_length=100, null=True)),
                ('tempoTotal', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
