# Generated by Django 5.0.3 on 2024-04-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_portalrealizeencerradas'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabricksFatoMailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.IntegerField(null=True)),
                ('dataMailing', models.DateField(null=True)),
                ('familia', models.CharField(max_length=10, null=True)),
                ('segmento', models.CharField(max_length=20, null=True)),
                ('faixaAtraso', models.CharField(max_length=10, null=True)),
                ('momentoAtraso', models.CharField(max_length=20, null=True)),
                ('propensao', models.CharField(max_length=20, null=True)),
                ('qtdClientes', models.IntegerField(null=True)),
                ('valorAtraso', models.FloatField(null=True)),
                ('valorSaldo', models.FloatField(null=True)),
                ('qtdTentativas', models.IntegerField(null=True)),
                ('qtdAlo', models.IntegerField(null=True)),
                ('qtdLocalizado', models.IntegerField(null=True)),
                ('qtdCpc', models.IntegerField(null=True)),
                ('qtdTarget', models.IntegerField(null=True)),
                ('qtdSucesso', models.IntegerField(null=True)),
                ('qtdTentativasUnique', models.IntegerField(null=True)),
                ('qtdAloUnique', models.IntegerField(null=True)),
                ('qtdLocalizadoUnique', models.IntegerField(null=True)),
                ('qtdCpcUnique', models.IntegerField(null=True)),
                ('qtdTargetUnique', models.IntegerField(null=True)),
                ('qtdSucessoUnique', models.IntegerField(null=True)),
                ('qtdPagamentoUnique', models.IntegerField(null=True)),
                ('qtdDiasMailing', models.IntegerField(null=True)),
            ],
        ),
    ]
