# Generated by Django 5.0.3 on 2024-04-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_databricksfatomailing'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabricksAnaliticoNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.IntegerField(null=True)),
                ('periodoNegocio', models.IntegerField(null=True)),
                ('periodoVencimento', models.IntegerField(null=True)),
                ('periodoPagamento', models.IntegerField(null=True)),
                ('tipoNegocio', models.CharField(max_length=20, null=True)),
                ('dataNegocio', models.DateField(null=True)),
                ('dataVencimento', models.DateField(null=True)),
                ('dataPagamento', models.DateField(null=True)),
                ('cpf', models.CharField(max_length=11, null=True)),
                ('usuario', models.CharField(max_length=20, null=True)),
                ('diasAtraso', models.IntegerField(null=True)),
                ('segmento', models.CharField(max_length=20, null=True)),
                ('familia', models.CharField(max_length=20, null=True)),
                ('faixaAtraso', models.CharField(max_length=10, null=True)),
                ('canal', models.CharField(max_length=20, null=True)),
                ('qtdNegocios', models.IntegerField(null=True)),
                ('qtdPagamentos', models.IntegerField(null=True)),
                ('qtdQuebras', models.IntegerField(null=True)),
                ('parcelamento', models.IntegerField(null=True)),
                ('faixaParcelamento', models.CharField(max_length=20, null=True)),
                ('diasVencimento', models.IntegerField(null=True)),
                ('nomeColaborador', models.CharField(max_length=100, null=True)),
                ('nomeLider', models.CharField(max_length=100, null=True)),
                ('tipoCargo', models.CharField(max_length=50, null=True)),
                ('valorDivida', models.FloatField(null=True)),
                ('valorNegociado', models.FloatField(null=True)),
                ('valorPagamento', models.FloatField(null=True)),
                ('valorSaldoCadoc', models.FloatField(null=True)),
                ('faixaAtrasoCadoc', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
