# Generated by Django 5.0.3 on 2024-05-10 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_databricksanaliticonegocio'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabricksAnaliticoMailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataMailing', models.DateField(null=True)),
                ('cpf', models.CharField(max_length=11, null=True)),
                ('digitoRandomico', models.CharField(max_length=2, null=True)),
                ('mailing', models.CharField(max_length=100, null=True)),
                ('faixaAtraso', models.CharField(max_length=50, null=True)),
                ('familia', models.CharField(max_length=50, null=True)),
                ('segmento', models.CharField(max_length=50, null=True)),
                ('grupoOperacao', models.CharField(max_length=50, null=True)),
                ('momentoAtraso', models.CharField(max_length=50, null=True)),
                ('propensao', models.CharField(max_length=50, null=True)),
                ('statusTratador', models.CharField(max_length=50, null=True)),
                ('idade', models.IntegerField(null=True)),
                ('cidade', models.CharField(max_length=100, null=True)),
                ('estado', models.CharField(max_length=2, null=True)),
                ('saldoCadoc', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Mailing',
        ),
    ]
