# Generated by Django 5.0.3 on 2024-05-10 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_databricksanaliticomailing_delete_mailing'),
    ]

    operations = [
        migrations.AddField(
            model_name='databricksanaliticomailing',
            name='dataNascimento',
            field=models.DateField(null=True),
        ),
    ]
